FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED=1
    
RUN pip install pipenv
COPY Pipfile .
COPY Pipfile.lock .

RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --dev --deploy
ENV PATH="/.venv/bin:$PATH"

COPY hasker/ hasker/
WORKDIR /hasker/
