FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED=1
    
RUN pip install pipenv
COPY Pipfile .
COPY Pipfile.lock .

RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy
ENV PATH="/.venv/bin:$PATH"
RUN pip install uwsgi

COPY hasker/ hasker/
COPY .root.crt /hasker/root.crt
WORKDIR /hasker/
