FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE 1

RUN pip install pipenv
COPY app/Pipfile .
COPY app/Pipfile.lock .

RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --dev --deploy
ENV PATH="/.venv/bin:$PATH"

COPY app/ app/
COPY tests/ app/tests
