version: '3'
services:
  scoring-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python app/api.py
    ports: 
      - 8080:8080
    depends_on: 
      - redis

  redis:
    image: docker.io/bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local
